### ISSUE TITLE
As a user I can display a catalog cover and download the PDF

### ISSUE THREAD

**Issue by sschafft** [the-petting-zoo/petting-zoo-relaunch#12]
As a user
When I [GO SOMEWHERE]
I can see an image of the catalog cover and a button to download the catalog

**Technical Steps**
- [ ] Determine where this needs to exist or how this needs to function in #7 
- [ ] Adjust current catalog content type and add to Netlify CMS
- [ ] Adjust asset hosting as needed
- [x] Implement any design adjustments needed.

**Comment by sschafft** [comment]
@jayperryworks - I am not entirely clear how / where this catalog cover thing fits in to the grid listing. Maybe something to explore in wireframing. I would guess it makes sense to have individual "catalog" pages with a product listing for that catalog along with the catalog cover image and download. We could then also have a similar non-filtered list for ALL products if thats useful. But not sure where the client stands on this.

**Comment by jayperryworks** [comment]
@sschafft oh, the idea is that, instead of displaying entire catalogs in a carousel, as the current site does, we'll show individual product listings in a grid, and then, somewhere nearby (up top?) there'll be a little card with a thumb of the catalog cover and a link to download the whole PDF. 

That way you can click through products on the site, or download the PDF to read the catalog there. Make sense?

**Comment by jayperryworks** [comment]
So this is tangentially related to #11, in that it's a UI element that will live on a 'catalog' page alongside the product listings.
